version: '0.0.1'

services:
  notebook:
    build: .
    ports:
      - "8888:8888"
      - "5000:5000"
    volumes:
      - "./data:/app/data"
    depends_on:
      - db
  
    
  db:
    build: ./database_docker
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"